title: 'Willkommen in Vietnam'
default_lang: ger
author:
  name: 'Phil Reiss'
  email: reiss_philipp@web.de
taxonomies:
  - category
  - tag
metadata:
  description: 'Reiseblog '
  author: 'Philipp Reiss'
  keywords: 'blog, travelling, writing, Vietnam, Asien, Reisen, Ho Chi Minh'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
  title: Mediator
description: ''
logo: user/logo.png
date_long: 'd F Y'
date_short: 'd M Y'
